/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/diagnosis-history` | `/diagnosis-history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/diagnosis-result` | `/diagnosis-result`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/diagnosis` | `/diagnosis`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome1`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome3`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/diagnosis-history` | `/diagnosis-history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/diagnosis-result` | `/diagnosis-result`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/diagnosis` | `/diagnosis`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/scan` | `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/welcome1`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/welcome2`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/welcome3`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/diagnosis-history${`?${string}` | `#${string}` | ''}` | `/diagnosis-history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/diagnosis-result${`?${string}` | `#${string}` | ''}` | `/diagnosis-result${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/diagnosis${`?${string}` | `#${string}` | ''}` | `/diagnosis${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/scan${`?${string}` | `#${string}` | ''}` | `/scan${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/welcome1${`?${string}` | `#${string}` | ''}` | `/onboarding/welcome2${`?${string}` | `#${string}` | ''}` | `/onboarding/welcome3${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/diagnosis-history` | `/diagnosis-history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/diagnosis-result` | `/diagnosis-result`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/diagnosis` | `/diagnosis`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome1`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome3`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
